# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        password: ${{secrets.SERVER_PASSWORD}}
        host: ${{secrets.SERVER_IP}}
        username: ${{secrets.SERVER_USERNAME}}
        script: |
          cd /root/Car-mkd-systems
          sudo git pull
          sudo npm install
          nx affected:build --all --prod
          sudo cp -r ~/Car-mkd-systems/dist/apps/web/* /var/www/car-mkd-systems.ru/html
          sudo pm2 restart 0
